# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: psycareer.ru
email: dmitry.bartoshevich@psycareer.ru
description: >
  Все для развития психолога
logo: "/assets/images/128.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.psycareer.ru" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Дмитрий Бартошевич'
bio: >
 Я&nbsp;маркетолог, автор psycareer.ru. Помогаю психологам находить клиентов и&nbsp;зарабатывать частными консультациями. 
author_image: "/assets/images/author.jpg"
twitter_username: psycareer
github_username:  #     jekyll

# Google Analytics
analytics_id: "UA-18892877-2"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  
 
  
    
 # Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
