
# site name
name: psycareer.ru

# Short description
description: маркетолог, консультант по маркетингу

# URL of avatar or profile pic
avatar: 

#
# Flags below are optional
#

# Used for Sitemap.xml and your RSS feed
url: https://psycareer.ru

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


permalink: /:title/

excerpt_separator: <!--more-->


# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as i'm using @imports
sass:
  style: :compressed #:expanded or :compressed

sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
        - "/me.markdown"
        - "/blog.markdown"
        - "/contact.markdown"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# Use the following plug-ins
# plugins:
#   - jekyll-assets
#   - autoprefixer-rails
#   - octopress-autoprefixer



#assets:
#  autoprefixer:
#    browsers:
#    - "last 2 versions"
#    - "IE > 9"



# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
